# Generated by Django 5.2.6 on 2025-09-19

from django.db import migrations

def seed_initial_data(apps, schema_editor):
    Language = apps.get_model("langleveltopics", "Language")
    LangName = apps.get_model("langleveltopics", "LangName")
    Level = apps.get_model("langleveltopics", "Level")

    # --- Languages ---
    langs = [
        ("de_DE", "Deutsch"),
        ("en_GB", "English"),
        ("es_ES", "Español"),
        ("ga_IE", "Gaeilge"),
    ]
    for iso, name in langs:
        lang = Language.objects.create(iso_code=iso)
        # Create a LangName entry for this language in itself
        LangName.objects.create(
            name_text=name,
            lang_iso=lang,
            text_iso=lang,  # name written in the same language
        )

    # --- Levels ---
    levels = ["A1", "A2", "B1", "B2", "C1", "C2"]
    for code in levels:
        Level.objects.create(code=code)


def undo_seed(apps, schema_editor):
    Language = apps.get_model("langleveltopics", "Language")
    LangName = apps.get_model("langleveltopics", "LangName")
    Level = apps.get_model("langleveltopics", "Level")

    LangName.objects.all().delete()
    Language.objects.all().delete()
    Level.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("langleveltopics", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_initial_data, undo_seed),
    ]
