# Generated by Django 5.2.6 on 2025-09-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Ordering for levels (1..6)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=200)),
                ('foreign_names', models.JSONField(blank=True, default=dict)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='langleveltopics.language')),
            ],
            options={
                'unique_together': {('language', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=200)),
                ('foreign_names', models.JSONField(blank=True, default=dict)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='langleveltopics.level')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='langleveltopics.theme')),
            ],
            options={
                'unique_together': {('theme', 'level', 'key')},
            },
        ),
        migrations.CreateModel(
            name='LangName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('lang_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='langleveltopics.language')),
                ('text_iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='langleveltopics.language')),
            ],
            options={
                'unique_together': {('lang_iso', 'text_iso')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langleveltopics.language')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='langleveltopics.topic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('topic', 'language', 'order')},
            },
        ),
    ]
