# Generated by Django 5.2.6 on 2025-09-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langleveltopics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
