# Generated by Django 5.2.6 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langleveltopics', '0003_seed_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
