# Generated by Django 5.2.6 on 2025-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langleveltopics', '0004_remove_section_text_alter_section_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
