# Generated by Django 5.2.6 on 2025-09-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langleveltopics', '0005_section_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langname',
            options={'verbose_name': 'Language name'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['level__order', 'order']},
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ordering within the level/theme'),
        ),
    ]
