# Generated by Django 5.2.6 on 2025-09-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langleveltopics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.JSONField(default=dict)),
                ('body', models.JSONField(default=list)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langleveltopics.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langleveltopics.level')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langleveltopics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('solutions', models.JSONField(default=list)),
                ('levels', models.ManyToManyField(to='langleveltopics.level')),
                ('topics', models.ManyToManyField(to='langleveltopics.topic')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.lesson')),
            ],
        ),
    ]
